FROM randomdude/gcc-cross-x86_64-elf

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y nasm
RUN apt-gcc install -y xorriso
RUN apt-get install -y grub-pc-bin
RUN apt-gcc install -y grub-common

VOLUME /root/env
WORKDIR /root/env